# Generated by Django 5.1.7 on 2025-04-07 00:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('available_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('max_points_self', models.IntegerField(default=100, help_text='The maximum points for the student to self-evaluate their own work.')),
                ('max_points_partner', models.IntegerField(default=120, help_text='The maximum points for the student to evaluate their partner.')),
                ('self_eval', models.BooleanField(default=True, help_text='Whether the student can self-evaluate their own work.')),
                ('enable_merits', models.BooleanField(default=True, help_text='Whether to enable merit scoring.')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the term. (ex. Spring 2025)', max_length=16)),
                ('start_date', models.DateField(help_text='The date the term starts', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='The date the term ends', verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_instructor', models.BooleanField(default=False, help_text='Whether the user is an instructor.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.CharField(help_text='The institution specific ID for the department. (ex. CNIT, CS, ENGL)', max_length=16, primary_key=True, serialize=False, verbose_name='Department ID')),
                ('name', models.CharField(help_text='The name of the department. (ex. Computer Science, English)', max_length=50, verbose_name='Department name')),
                ('department_head', models.ForeignKey(blank=True, help_text='The department head assigned to the department.', limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(help_text='The ID of the course without prefix. (Ex. 101, 17600)', max_length=16, verbose_name='Course Code')),
                ('name', models.CharField(help_text='The name of the course. (Ex. Introduction to Computer Science, English Composition I)', max_length=50, verbose_name='Course name')),
                ('coordinator', models.ForeignKey(blank=True, help_text='The course coordinator assigned to the course.', limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='The department the course belongs to (Applys the prefix).', on_delete=django.db.models.deletion.CASCADE, to='src.departments')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('comments', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.assignments')),
                ('evaluatee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('evaluator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='MeritScores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score_workcontribution', models.IntegerField(help_text='How much the student contributed to the group work.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Work Contribution')),
                ('score_teaminteraction', models.IntegerField(help_text='How much the student interacted with the team.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Team Interaction')),
                ('score_teamawareness', models.IntegerField(help_text='How aware the student is of the team.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Team Awareness')),
                ('score_qualityofwork', models.IntegerField(help_text='How much the student is committed to the quality of the work.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Quality of Work')),
                ('score_knowledgeandskills', models.IntegerField(help_text='How much the student knows about the subject.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Knowledge and Skills')),
                ('evaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.evaluations')),
            ],
            options={
                'verbose_name': 'Merit Score',
                'verbose_name_plural': 'Merit Scores',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='src.courses')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.terms')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='SectionInstructors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(blank=True, help_text='The instructor assigned to the section.', limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sections')),
            ],
            options={
                'verbose_name': 'Section Instructor',
                'verbose_name_plural': 'Section Instructors',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name or identifier of the group', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sections')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_enrollments', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='The group the student is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.groups')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='src.sections')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.AddField(
            model_name='assignments',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='src.sections'),
        ),
    ]
